name: qlevar_local_manager
description: This app will help you manage you applications locals easily. set you locals in groups, translate them with google translation and then export them to a class that is useable with Getx.
publish_to: 'none' 
version: 1.3.0
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.11
  reactive_state:
    path: ../reactive_state
  http: ^0.13.4
  file_picker: ^4.3.2
  q_overlay:
    git: https://github.com/SchabanBo/q_overlay.git
  get_it: ^7.2.0
    
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
flutter:
  uses-material-design: true